namespace ToroLogType {
	enum
	{
		none,
		common_installed,
		common_register,
		common_login,
		common_adid,
		common_iap,
		common_prepurchase,
		common_gem,
		common_mail_create,
		common_mail_receive,
		common_mail_delete,
		common_duration,
		common_tutorial,
		common_player_level,
		common_nickname,
		star,
		heart,
		heart_invincible,
		puzzle_start,
		puzzle_finish,
		puzzle_continue,
		item,
		furniture,
		furniture_change,
		costume,
		costume_change,
		pokepi,
		_friend, // renamed from `friend` because c++
		friend_request,
		friend_heart,
		story,
		memory,
		dictionary,
		shop_buy,
		ad_impression,
		ad_request,
		ad_reward,
		title_change,
		icon_change,
		achivement,
		attendance,
		block,
	};
};

namespace CommonDurationTag {
	enum
	{
		none,
		Field,
		Puzzle,
		Post,
		Event,
		EventShop,
		Story,
		Diary,
		FieldMap,
		Room,
		Post_Heart,
		Post_Present,
		Room_Friend,
		Room_Friend_My,
		Room_Friend_My_Friend,
		Room_Friend_Search,
		Room_Friend_Request,
		Room_Pokepi_Toro,
		Room_Pokepi_Sora,
		Room_Pokepi_Jun,
		Room_Pokepi_Suzuki,
		Room_Pokepi_Kuro,
		Room_Pokepi_Pierre,
		Room_Pokepi_Ricky,
		Room_Pokepi_Toro_0,
		Room_Pokepi_Toro_1,
		Room_Pokepi_Toro_2,
		Room_Pokepi_Toro_3,
		Room_Pokepi_Toro_4,
		Room_Pokepi_Sora_0,
		Room_Pokepi_Sora_1,
		Room_Pokepi_Sora_2,
		Room_Pokepi_Kuro_0,
		Room_Pokepi_Kuro_1,
		Room_Pokepi_Pierre_0,
		Room_Pokepi_Pierre_1,
		Room_Pokepi_Pierre_2,
		Room_Pokepi_Ricky_0,
		Room_Pokepi_Ricky_1,
		Room_Pokepi_Ricky_2,
		Room_Pokepi_Ricky_3,
		Field_Pokepi_Toro,
		Field_Pokepi_Sora,
		Field_Pokepi_Jun,
		Field_Pokepi_Suzuki,
		Field_Pokepi_Kuro,
		Field_Pokepi_Pierre,
		Field_Pokepi_Ricky,
		Field_Pokepi_Toro_0,
		Field_Pokepi_Toro_1,
		Field_Pokepi_Toro_2,
		Field_Pokepi_Toro_3,
		Field_Pokepi_Toro_4,
		Field_Pokepi_Sora_0,
		Field_Pokepi_Sora_1,
		Field_Pokepi_Sora_2,
		Field_Pokepi_Kuro_0,
		Field_Pokepi_Kuro_1,
		Field_Pokepi_Pierre_0,
		Field_Pokepi_Pierre_1,
		Field_Pokepi_Pierre_2,
		Field_Pokepi_Ricky_0,
		Field_Pokepi_Ricky_1,
		Field_Pokepi_Ricky_2,
		Field_Pokepi_Ricky_3,
	};
};

namespace PlatformID
{
	enum
	{
		None = -1,
		Kakao = 8,
		Facebook = 20,
		GooglePlay = 30,
		GoogleSignIn,
		AppleGameCenter = 40,
		AppleSignIn,
		Twitter = 50,
		Email = 60,
		LineOpenAPI = 70,
		Line_Channeling = 73,
		LineTridentLite,
		Steam = 80,
		Guest = 99,
		Dev_windows = 88
	};
};